# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ups.proto',
  package='',
  serialized_pb=_b('\n\tups.proto\"6\n\x08UConnect\x12\x13\n\x0breconnectid\x18\x01 \x01(\x03\x12\x15\n\rnumtrucksinit\x18\x02 \x01(\x05\",\n\nUConnected\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"*\n\tUGoPickup\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x0c\n\x04whid\x18\x02 \x02(\x05\"2\n\tUFinished\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\t\n\x01x\x18\x02 \x02(\x05\x12\t\n\x01y\x18\x03 \x02(\x05\"3\n\rUDeliveryMade\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x11\n\tpackageid\x18\x02 \x02(\x03\"<\n\x11UDeliveryLocation\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\t\n\x01x\x18\x02 \x02(\x05\x12\t\n\x01y\x18\x03 \x02(\x05\"C\n\nUGoDeliver\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12$\n\x08packages\x18\x02 \x03(\x0b\x32\x12.UDeliveryLocation\"o\n\tUCommands\x12\x1f\n\ndeliveries\x18\x01 \x03(\x0b\x32\x0b.UGoDeliver\x12\x1b\n\x07pickups\x18\x02 \x03(\x0b\x32\n.UGoPickup\x12\x10\n\x08simspeed\x18\x03 \x01(\r\x12\x12\n\ndisconnect\x18\x04 \x01(\x08\"q\n\nUResponses\x12\x1f\n\x0b\x63ompletions\x18\x01 \x03(\x0b\x32\n.UFinished\x12!\n\tdelivered\x18\x02 \x03(\x0b\x32\x0e.UDeliveryMade\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x10\n\x08\x66inished\x18\x04 \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UCONNECT = _descriptor.Descriptor(
  name='UConnect',
  full_name='UConnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reconnectid', full_name='UConnect.reconnectid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numtrucksinit', full_name='UConnect.numtrucksinit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=67,
)


_UCONNECTED = _descriptor.Descriptor(
  name='UConnected',
  full_name='UConnected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='UConnected.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='UConnected.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=113,
)


_UGOPICKUP = _descriptor.Descriptor(
  name='UGoPickup',
  full_name='UGoPickup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UGoPickup.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='whid', full_name='UGoPickup.whid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=157,
)


_UFINISHED = _descriptor.Descriptor(
  name='UFinished',
  full_name='UFinished',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UFinished.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='UFinished.x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='UFinished.y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=209,
)


_UDELIVERYMADE = _descriptor.Descriptor(
  name='UDeliveryMade',
  full_name='UDeliveryMade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UDeliveryMade.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packageid', full_name='UDeliveryMade.packageid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=262,
)


_UDELIVERYLOCATION = _descriptor.Descriptor(
  name='UDeliveryLocation',
  full_name='UDeliveryLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='UDeliveryLocation.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='UDeliveryLocation.x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='UDeliveryLocation.y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=324,
)


_UGODELIVER = _descriptor.Descriptor(
  name='UGoDeliver',
  full_name='UGoDeliver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UGoDeliver.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packages', full_name='UGoDeliver.packages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=393,
)


_UCOMMANDS = _descriptor.Descriptor(
  name='UCommands',
  full_name='UCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deliveries', full_name='UCommands.deliveries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pickups', full_name='UCommands.pickups', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='simspeed', full_name='UCommands.simspeed', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disconnect', full_name='UCommands.disconnect', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=506,
)


_URESPONSES = _descriptor.Descriptor(
  name='UResponses',
  full_name='UResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='completions', full_name='UResponses.completions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delivered', full_name='UResponses.delivered', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='UResponses.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='finished', full_name='UResponses.finished', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=621,
)

_UGODELIVER.fields_by_name['packages'].message_type = _UDELIVERYLOCATION
_UCOMMANDS.fields_by_name['deliveries'].message_type = _UGODELIVER
_UCOMMANDS.fields_by_name['pickups'].message_type = _UGOPICKUP
_URESPONSES.fields_by_name['completions'].message_type = _UFINISHED
_URESPONSES.fields_by_name['delivered'].message_type = _UDELIVERYMADE
DESCRIPTOR.message_types_by_name['UConnect'] = _UCONNECT
DESCRIPTOR.message_types_by_name['UConnected'] = _UCONNECTED
DESCRIPTOR.message_types_by_name['UGoPickup'] = _UGOPICKUP
DESCRIPTOR.message_types_by_name['UFinished'] = _UFINISHED
DESCRIPTOR.message_types_by_name['UDeliveryMade'] = _UDELIVERYMADE
DESCRIPTOR.message_types_by_name['UDeliveryLocation'] = _UDELIVERYLOCATION
DESCRIPTOR.message_types_by_name['UGoDeliver'] = _UGODELIVER
DESCRIPTOR.message_types_by_name['UCommands'] = _UCOMMANDS
DESCRIPTOR.message_types_by_name['UResponses'] = _URESPONSES

UConnect = _reflection.GeneratedProtocolMessageType('UConnect', (_message.Message,), dict(
  DESCRIPTOR = _UCONNECT,
  __module__ = 'ups_pb2'
  # @@protoc_insertion_point(class_scope:UConnect)
  ))
_sym_db.RegisterMessage(UConnect)

UConnected = _reflection.GeneratedProtocolMessageType('UConnected', (_message.Message,), dict(
  DESCRIPTOR = _UCONNECTED,
  __module__ = 'ups_pb2'
  # @@protoc_insertion_point(class_scope:UConnected)
  ))
_sym_db.RegisterMessage(UConnected)

UGoPickup = _reflection.GeneratedProtocolMessageType('UGoPickup', (_message.Message,), dict(
  DESCRIPTOR = _UGOPICKUP,
  __module__ = 'ups_pb2'
  # @@protoc_insertion_point(class_scope:UGoPickup)
  ))
_sym_db.RegisterMessage(UGoPickup)

UFinished = _reflection.GeneratedProtocolMessageType('UFinished', (_message.Message,), dict(
  DESCRIPTOR = _UFINISHED,
  __module__ = 'ups_pb2'
  # @@protoc_insertion_point(class_scope:UFinished)
  ))
_sym_db.RegisterMessage(UFinished)

UDeliveryMade = _reflection.GeneratedProtocolMessageType('UDeliveryMade', (_message.Message,), dict(
  DESCRIPTOR = _UDELIVERYMADE,
  __module__ = 'ups_pb2'
  # @@protoc_insertion_point(class_scope:UDeliveryMade)
  ))
_sym_db.RegisterMessage(UDeliveryMade)

UDeliveryLocation = _reflection.GeneratedProtocolMessageType('UDeliveryLocation', (_message.Message,), dict(
  DESCRIPTOR = _UDELIVERYLOCATION,
  __module__ = 'ups_pb2'
  # @@protoc_insertion_point(class_scope:UDeliveryLocation)
  ))
_sym_db.RegisterMessage(UDeliveryLocation)

UGoDeliver = _reflection.GeneratedProtocolMessageType('UGoDeliver', (_message.Message,), dict(
  DESCRIPTOR = _UGODELIVER,
  __module__ = 'ups_pb2'
  # @@protoc_insertion_point(class_scope:UGoDeliver)
  ))
_sym_db.RegisterMessage(UGoDeliver)

UCommands = _reflection.GeneratedProtocolMessageType('UCommands', (_message.Message,), dict(
  DESCRIPTOR = _UCOMMANDS,
  __module__ = 'ups_pb2'
  # @@protoc_insertion_point(class_scope:UCommands)
  ))
_sym_db.RegisterMessage(UCommands)

UResponses = _reflection.GeneratedProtocolMessageType('UResponses', (_message.Message,), dict(
  DESCRIPTOR = _URESPONSES,
  __module__ = 'ups_pb2'
  # @@protoc_insertion_point(class_scope:UResponses)
  ))
_sym_db.RegisterMessage(UResponses)


# @@protoc_insertion_point(module_scope)
