CFLAGS=-Wall -Werror --std=gnu99 --pedantic
all: square square_broken

square: square.c
	gcc -o square $(CFLAGS) square.c

square_broken: square_broken.c
	gcc -o square_broken $(CFLAGS) square_broken.c

