# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_info', '0002_auto_20170502_0447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'managed': False},
        ),
    ]
