# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170301_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pri_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_type', models.IntegerField(default=1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paa_set', to='polls.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pau_set', to='polls.User')),
            ],
        ),
        migrations.CreateModel(
            name='Pri_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe_type', models.IntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pee_set', to='polls.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peu_set', to='polls.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='user',
        ),
        migrations.DeleteModel(
            name='Privilege',
        ),
    ]
