# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170302_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='e_date',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
